# Generated by Django 5.2.13 on 2026-04-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_captchamodel_loginattemptlockout_failedloginattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_scratch',
            field=models.BooleanField(default=False, help_text='Whether website was created from scratch (no template)'),
        ),
    ]
