# Generated by Django 5.2.13 on 2026-04-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_is_scratch_to_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='initial_content',
            field=models.TextField(blank=True, help_text='Initial HTML content for scratch websites'),
        ),
    ]
