# Generated by Django 5.0.4 on 2026-04-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_hosting_disk_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWebsiteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('zip_file', models.FileField(help_text='Uploaded ZIP file', upload_to='uploads/websites/%Y/%m/')),
                ('extracted_path', models.CharField(blank=True, help_text='Path to extracted files', max_length=500)),
                ('source', models.CharField(choices=[('upload', 'User Upload'), ('template_convert', 'Template Conversion')], default='upload', max_length=20)),
                ('status', models.CharField(default='pending', help_text='pending, extracting, ready, failed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTemplateJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('json_structure', models.JSONField(help_text='JSON structure for page builder')),
                ('source_html', models.TextField(blank=True, help_text='Original HTML content')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_templates', to='core.customwebsiteupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customwebsiteupload',
            index=models.Index(fields=['owner', '-created_at'], name='core_custom_owner_i_70991c_idx'),
        ),
        migrations.AddIndex(
            model_name='customwebsiteupload',
            index=models.Index(fields=['slug'], name='core_custom_slug_f7f611_idx'),
        ),
        migrations.AddIndex(
            model_name='customwebsiteupload',
            index=models.Index(fields=['status'], name='core_custom_status_cd4596_idx'),
        ),
        migrations.AddIndex(
            model_name='websitetemplatejson',
            index=models.Index(fields=['slug'], name='core_websit_slug_7dc23b_idx'),
        ),
        migrations.AddIndex(
            model_name='websitetemplatejson',
            index=models.Index(fields=['is_active'], name='core_websit_is_acti_4d29f2_idx'),
        ),
    ]
