# Generated by Django 5.0.4 on 2026-04-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customwebsiteupload_websitetemplatejson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customwebsiteupload',
            name='database_imported',
            field=models.BooleanField(default=False, help_text='Database imported successfully'),
        ),
        migrations.AddField(
            model_name='customwebsiteupload',
            name='sql_files',
            field=models.JSONField(blank=True, default=list, help_text='SQL files found in ZIP'),
        ),
    ]
