# Generated by Django 5.0.4 on 2026-04-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customwebsiteupload_database_imported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='email_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='email_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
