# Generated by Django 5.0.4 on 2026-05-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_email_code_expires_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_email_v_79951d_idx',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='email_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='email_code_expires',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_code_expires',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
    ]
