# Generated by Django 5.0.4 on 2026-05-02 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_userprofile_core_userpr_email_v_79951d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customwebsiteupload',
            name='database_imported',
        ),
        migrations.RemoveField(
            model_name='customwebsiteupload',
            name='sql_files',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email_verification_token'], name='core_userpr_email_v_79951d_idx'),
        ),
    ]
