# Generated by Django 5.0.4 on 2026-05-19 14:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_customwebsiteupload_database_imported_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWebsiteGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="User's text prompt for website generation")),
                ('generated_content', models.JSONField(default=dict, help_text='Generated website elements JSON')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('form_submission', 'Form Submission'), ('new_order', 'New Order'), ('product_created', 'Product Created'), ('visitor_count', 'Visitor Count'), ('time_based', 'Time Based')], max_length=50)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='Conditions for trigger')),
                ('action', models.CharField(choices=[('send_email', 'Send Email'), ('send_webhook', 'Send Webhook'), ('add_tag', 'Add Tag'), ('update_field', 'Update Field'), ('create_task', 'Create Task')], max_length=50)),
                ('action_data', models.JSONField(default=dict, help_text='Data for the action')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description of the post')),
                ('content', models.TextField(help_text='Full post content (HTML supported)')),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='For guest users', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('purchase', 'Purchase'), ('newsletter_signup', 'Newsletter Signup'), ('contact_form', 'Contact Form Submission'), ('lead', 'Lead Generation'), ('custom', 'Custom Event')], max_length=30)),
                ('name', models.CharField(help_text='Conversion name', max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value', max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('shipping', 'Free Shipping')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount', max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_limit', models.IntegerField(default=0, help_text='0 for unlimited, else max uses')),
                ('used_count', models.IntegerField(default=0)),
                ('per_customer_limit', models.IntegerField(default=0, help_text='0 for unlimited per customer')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='HTML content')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text version')),
                ('from_name', models.CharField(default='noreply', max_length=100)),
                ('from_email', models.EmailField(default='noreply@example.com', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_list', models.JSONField(default=list, help_text='List of recipient emails or segment ID')),
                ('include_subscribers', models.BooleanField(default=True)),
                ('include_customers', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('bounced_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('html', 'HTML/CSS/JS'), ('zip', 'ZIP Archive'), ('github', 'GitHub Repository')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Exported file', null=True, upload_to='exports/%Y/%m/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fields', models.JSONField(default=list, help_text='List of field definitions (type, label, required, etc.)')),
                ('submit_text', models.CharField(default='Submit', max_length=50)),
                ('success_message', models.TextField(blank=True, default='Thank you for your submission!')),
                ('email_notifications', models.JSONField(blank=True, default=list, help_text='List of emails to notify')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name (for backend)', max_length=100)),
                ('label', models.CharField(help_text='Field label (for user)', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('tel', 'Telephone'), ('textarea', 'Textarea'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File Upload'), ('date', 'Date'), ('number', 'Number')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Options for select/radio fields')),
                ('validation', models.JSONField(blank=True, default=dict, help_text='Validation rules (min, max, pattern, etc.)')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(help_text='Name/identifier of the form', max_length=100)),
                ('submission_data', models.JSONField(help_text='Submitted form data')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InstalledPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(default=dict, help_text='User-configured settings')),
                ('is_enabled', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='How they subscribed', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_name', models.CharField(max_length=200)),
                ('shipping_address_line1', models.CharField(max_length=200)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('billing_name', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('same_as_shipping', models.BooleanField(default=True)),
                ('items', models.JSONField(default=list, help_text='Snapshot of ordered products at time of purchase')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping fee', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial_refund', 'Partially Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='stripe, flutterwave, etc.', max_length=50, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Order notes/internal comments')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of product name', max_length=200)),
                ('variant_name', models.CharField(blank=True, help_text='Snapshot of variant', max_length=200, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Page display name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('title', models.CharField(help_text='Page title (for browser tab)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=500)),
                ('is_homepage', models.BooleanField(default=False, help_text='Is this the homepage?')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('settings_schema', models.JSONField(default=dict, help_text='JSON schema for plugin settings')),
                ('default_settings', models.JSONField(default=dict, help_text='Default plugin configuration')),
                ('is_builtin', models.BooleanField(default=False, help_text='Built into the platform')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True, help_text='Brief summary', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price', max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Length, width, height')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Option name (e.g., Size, Color)', max_length=100)),
                ('values', models.JSONField(default=list, help_text="List of option values (e.g., ['S', 'M', 'L'])")),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('options', models.JSONField(default=dict, help_text='e.g., {"Size": "M", "Color": "Red"}')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50, null=True)),
                ('google_search_console_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bing_webmaster_id', models.CharField(blank=True, max_length=100, null=True)),
                ('default_og_image', models.URLField(blank=True, help_text='Default Open Graph image', null=True)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /\nDisallow: /admin/', help_text='robots.txt content')),
                ('sitemap_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitemapUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(help_text='Full URL', max_length=500)),
                ('lastmod', models.DateTimeField(blank=True, null=True)),
                ('changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Webhook name', max_length=100)),
                ('url', models.URLField(help_text='Webhook endpoint URL')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers as JSON')),
                ('events', models.JSONField(default=list, help_text='Events to trigger this webhook')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitors', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('backup_data', models.JSONField(help_text='Backup of website elements and settings')),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_email_v_79951d_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='aiwebsitegeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiwebsitegeneration',
            name='website',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation', to='core.website'),
        ),
        migrations.AddField(
            model_name='automation',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='core.website'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.website'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user (null for guest carts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.website'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.category'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversion',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='core.website'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.website'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='core.website'),
        ),
        migrations.AddField(
            model_name='exportedwebsite',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.website'),
        ),
        migrations.AddField(
            model_name='form',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.website'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='core.form'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='core.website'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formsubmission'),
        ),
        migrations.AddField(
            model_name='installedplugin',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_plugins', to='core.website'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='core.website'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Registered user (null for guest checkout)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.website'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='core.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.website'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='core.website'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='required_plan',
            field=models.ForeignKey(blank=True, help_text='Plan required to use this plugin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billingplan'),
        ),
        migrations.AddField(
            model_name='installedplugin',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plugin'),
        ),
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.website'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='core.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_products',
            field=models.ManyToManyField(blank=True, related_name='excluded_coupons', to='core.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.website'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='core.website'),
        ),
        migrations.AddField(
            model_name='sitemapurl',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_urls', to='core.website'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.tag'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.website'),
        ),
        migrations.AddField(
            model_name='websiteanalytics',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.website'),
        ),
        migrations.AddField(
            model_name='websitebackup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websitebackup',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.website'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlisted_by', to='core.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='core.website'),
        ),
        migrations.AddIndex(
            model_name='aiwebsitegeneration',
            index=models.Index(fields=['user', '-created_at'], name='core_aiwebs_user_id_fb862f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiwebsitegeneration',
            index=models.Index(fields=['status'], name='core_aiwebs_status_07e301_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='core_cart_user_id_36d4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id', 'is_active'], name='core_cart_session_8ef55c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['website'], name='core_cart_website_ca6071_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['website', '-created_at'], name='core_emailc_website_b1232c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status'], name='core_emailc_status_d19fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='exportedwebsite',
            index=models.Index(fields=['website', '-created_at'], name='core_export_website_1dfbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='exportedwebsite',
            index=models.Index(fields=['status'], name='core_export_status_9954b4_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['website'], name='core_form_website_ee752b_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['slug'], name='core_form_slug_cd042d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('website', 'slug')},
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form'], name='core_formfi_form_id_f2e854_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['website', '-submitted_at'], name='core_formsu_website_f9fe00_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['website', 'is_active'], name='core_newsle_website_af6029_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['email'], name='core_newsle_email_c74825_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['website', '-created_at'], name='core_order_website_7cefc4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='core_order_order_n_6d2664_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='core_order_user_id_f84106_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='core_order_email_af2f89_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='core_order_payment_6639e3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['website', '-created_at'], name='core_conver_website_d1af33_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['conversion_type'], name='core_conver_convers_052ead_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user'], name='core_conver_user_id_867334_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['website', 'sort_order'], name='core_page_website_6f38f0_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='core_page_slug_904ec3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'slug')},
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', '-created_at'], name='core_pagevi_website_d69115_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_url'], name='core_pagevi_page_ur_45e684_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_id'], name='core_pagevi_session_86ebc3_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['created_at'], name='core_pagevi_created_d66d00_idx'),
        ),
        migrations.AddIndex(
            model_name='plugin',
            index=models.Index(fields=['slug'], name='core_plugin_slug_f9243f_idx'),
        ),
        migrations.AddIndex(
            model_name='plugin',
            index=models.Index(fields=['is_active'], name='core_plugin_is_acti_3b2681_idx'),
        ),
        migrations.AddIndex(
            model_name='installedplugin',
            index=models.Index(fields=['website', 'is_enabled'], name='core_instal_website_3f164f_idx'),
        ),
        migrations.AddIndex(
            model_name='installedplugin',
            index=models.Index(fields=['plugin'], name='core_instal_plugin__3c14db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installedplugin',
            unique_together={('website', 'plugin')},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['website'], name='core_coupon_website_825c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='core_coupon_code_4affe4_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='core_coupon_is_acti_3511a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['website'], name='core_produc_website_86afd6_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug'], name='core_produc_slug_ab1ff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('website', 'slug')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['website', '-created_at'], name='core_produc_website_2e3efe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='core_produc_slug_42f8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='core_produc_is_acti_ac2ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='core_produc_categor_784c92_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='core_produc_product_6a15f8_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='core_produc_rating_eb0280_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_approved'], name='core_produc_is_appr_50c2ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='core_cartit_cart_id_c09971_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='core_cartit_product_70953e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='sitemapurl',
            index=models.Index(fields=['website', 'is_active'], name='core_sitema_website_e8b2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='core_blogpo_slug_36a1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status'], name='core_blogpo_status_032da8_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='core_blogpo_publish_4753d4_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteanalytics',
            index=models.Index(fields=['website', '-date'], name='core_websit_website_3552ca_idx'),
        ),
        migrations.AddIndex(
            model_name='websitebackup',
            index=models.Index(fields=['website', '-created_at'], name='core_websit_website_d1ae28_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'website'], name='core_wishli_user_id_4611e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'website')},
        ),
    ]
