# Generated by Django 5.0.4 on 2026-06-03 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aiwebsitegeneration_automation_blogpost_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='route',
            field=models.CharField(blank=True, default='', help_text='Custom route path', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
