# Generated by Django migration for PaymentMethod

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_page_parent_page_route_alter_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('flutterwave_voucher', 'Flutterwave Virtual Card')], max_length=20)),
                ('type', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('flutterwave_voucher', 'Flutterwave Virtual Card')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('flutterwave_token', models.CharField(blank=True, help_text='Flutterwave payment token', max_length=255, null=True)),
                ('masked_number', models.CharField(blank=True, help_text='Masked account/card number', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='For mobile money', max_length=20, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=2)),
                ('expiry_year', models.CharField(blank=True, max_length=4)),
                ('card_holder_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='active', help_text='active, expired, removed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', '-is_default'], name='core_paymen_user_id_6e1a93_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['provider'], name='core_paymen_provide_6c6671_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['type'], name='core_paymen_type_703391_idx'),
        ),
    ]