# Generated by Django 4.2.8 on 2026-04-07 09:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_billingplan_template_usertemplate_userbillingplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=100)),
                ('verification_record', models.CharField(blank=True, max_length=100)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_cert_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='index', help_text='Page identifier (e.g., index, about, contact)', max_length=100)),
                ('element_type', models.CharField(choices=[('text', 'Text Block'), ('heading', 'Heading'), ('image', 'Image'), ('button', 'Button'), ('container', 'Container'), ('row', 'Row'), ('column', 'Column'), ('nav', 'Navigation'), ('footer', 'Footer'), ('hero', 'Hero Section'), ('gallery', 'Gallery'), ('form', 'Form'), ('video', 'Video'), ('map', 'Map'), ('social', 'Social Links'), ('divider', 'Divider'), ('spacer', 'Spacer')], max_length=50)),
                ('element_data', models.JSONField(default=dict, help_text='Element properties (style, content, attributes)')),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_name', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=50)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='template',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='seo_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='website',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites_created', to='core.template'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='description',
            field=models.TextField(blank=True, help_text='Plan description'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='max_templates_access',
            field=models.IntegerField(default=0, help_text='Templates access (0=none, -1=all)'),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='max_websites',
            field=models.IntegerField(default=1, help_text='Maximum number of websites allowed (-1 for unlimited)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='name',
            field=models.CharField(help_text='Plan name (e.g., Basic, Pro, Enterprise)', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobile_network',
            field=models.CharField(blank=True, choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('vodafone', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbillingplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='core.billingplan'),
        ),
        migrations.AlterField(
            model_name='website',
            name='content',
            field=models.TextField(blank=True, help_text='Main website content/HTML'),
        ),
        migrations.AddIndex(
            model_name='billingplan',
            index=models.Index(fields=['slug'], name='core_billin_slug_02bed1_idx'),
        ),
        migrations.AddIndex(
            model_name='billingplan',
            index=models.Index(fields=['price'], name='core_billin_price_eb21f1_idx'),
        ),
        migrations.AddIndex(
            model_name='billingplan',
            index=models.Index(fields=['is_active', 'price'], name='core_billin_is_acti_f93fec_idx'),
        ),
        migrations.AddIndex(
            model_name='billingplanfeature',
            index=models.Index(fields=['plan', 'feature_name'], name='core_billin_plan_id_09f337_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='core_invoic_user_id_5034e4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='core_invoic_created_ee75a3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='core_invoic_invoice_2fc0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='core_paymen_user_id_1df83c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription'], name='core_paymen_subscri_4f7002_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='core_paymen_status_8390cc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='core_paymen_created_f77624_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='core_paymen_stripe__c08188_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['slug'], name='core_templa_slug_61e10b_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category', 'is_active'], name='core_templa_categor_c17c83_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['price', 'is_free'], name='core_templa_price_cf77eb_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['-created_at'], name='core_templa_created_daa5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['-rating'], name='core_templa_rating_95ebba_idx'),
        ),
        migrations.AddIndex(
            model_name='templateorder',
            index=models.Index(fields=['user', '-created_at'], name='core_templa_user_id_71fe04_idx'),
        ),
        migrations.AddIndex(
            model_name='templateorder',
            index=models.Index(fields=['status'], name='core_templa_status_0092c8_idx'),
        ),
        migrations.AddIndex(
            model_name='templateorder',
            index=models.Index(fields=['order_type'], name='core_templa_order_t_5c442f_idx'),
        ),
        migrations.AddIndex(
            model_name='templatepurchase',
            index=models.Index(fields=['user', '-created_at'], name='core_templa_user_id_55e143_idx'),
        ),
        migrations.AddIndex(
            model_name='templatepurchase',
            index=models.Index(fields=['template'], name='core_templa_templat_51d726_idx'),
        ),
        migrations.AddIndex(
            model_name='templatepurchase',
            index=models.Index(fields=['payment_status'], name='core_templa_payment_31abac_idx'),
        ),
        migrations.AddIndex(
            model_name='userbillingplan',
            index=models.Index(fields=['user'], name='core_userbi_user_id_20315e_idx'),
        ),
        migrations.AddIndex(
            model_name='userbillingplan',
            index=models.Index(fields=['plan'], name='core_userbi_plan_id_042dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='usertemplate',
            index=models.Index(fields=['user', '-purchased_at'], name='core_userte_user_id_0e3d89_idx'),
        ),
        migrations.AddIndex(
            model_name='usertemplate',
            index=models.Index(fields=['template'], name='core_userte_templat_baf7be_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['owner', '-created_at'], name='core_websit_owner_i_d6cc66_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['slug'], name='core_websit_slug_ea52e8_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['status'], name='core_websit_status_a361fb_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['is_published'], name='core_websit_is_publ_7faa03_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['subdomain'], name='core_websit_subdoma_ad75a3_idx'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.website'),
        ),
        migrations.AddField(
            model_name='pageelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.pageelement'),
        ),
        migrations.AddField(
            model_name='pageelement',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_elements', to='core.website'),
        ),
        migrations.AddField(
            model_name='domain',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.website'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['website'], name='core_teamme_website_e8f581_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='core_teamme_user_id_f89466_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['role'], name='core_teamme_role_5bc5be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('website', 'user')},
        ),
        migrations.AddIndex(
            model_name='pageelement',
            index=models.Index(fields=['website', 'page_name'], name='core_pageel_website_20e794_idx'),
        ),
        migrations.AddIndex(
            model_name='pageelement',
            index=models.Index(fields=['page_name'], name='core_pageel_page_na_ef4aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['website'], name='core_domain_website_1ccc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain'], name='core_domain_domain_f8b322_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['is_verified'], name='core_domain_is_veri_3f47be_idx'),
        ),
    ]
