# Generated by Django 5.2.13 on 2026-04-15 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_initial_content_to_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='disk_space_gb',
            field=models.IntegerField(default=5, help_text='Disk space in GB (-1 for unlimited)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='hosting_type',
            field=models.CharField(choices=[('shared', 'Shared Hosting'), ('vps', 'VPS Hosting'), ('dedicated', 'Dedicated Server'), ('cloud', 'Cloud Hosting')], default='shared', help_text='Type of hosting for this plan', max_length=20),
        ),
    ]
